# Generated by Django 4.1 on 2022-08-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0006_alter_countrystats_country_actives_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountryStats',
            new_name='CountryInfo',
        ),
    ]
