# Generated by Django 4.1 on 2022-08-04 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('covid', '0003_alter_country_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='userName',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
