# Generated by Django 4.1 on 2022-08-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_alter_country_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryStats',
            fields=[
                ('country_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('country_deaths', models.IntegerField(max_length=100)),
                ('country_recovered', models.IntegerField(max_length=100)),
                ('country_confirmed', models.IntegerField(max_length=100)),
                ('country_actives', models.IntegerField(max_length=100)),
            ],
        ),
    ]
