# Generated by Django 4.1 on 2022-08-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0005_countrystats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrystats',
            name='country_actives',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='countrystats',
            name='country_confirmed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='countrystats',
            name='country_deaths',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='countrystats',
            name='country_recovered',
            field=models.IntegerField(),
        ),
    ]
